'use client';

import { useState } from 'react';
import { Icon } from '../../components';
import { PortalShell, RequireRole } from '../../portal-shell';

const patients = [{ name: 'Maya Patel', initials: 'MP', age: 34, last: 'Today, 9:12 AM', checks: 'Wellbeing, heart', status: 'Ready', tone: 'good' }, { name: 'Arjun Kumar', initials: 'AK', age: 51, last: 'Yesterday, 5:40 PM', checks: 'Blood pressure', status: 'Review', tone: 'warm' }, { name: 'Sana Mehta', initials: 'SM', age: 29, last: 'Yesterday, 3:15 PM', checks: 'Lab results', status: 'New', tone: 'blue' }, { name: 'Rohan Jain', initials: 'RJ', age: 45, last: '30 Aug, 10:00 AM', checks: 'Diabetes risk', status: 'Ready', tone: 'good' }, { name: 'Priya Nair', initials: 'PN', age: 38, last: '29 Aug, 2:20 PM', checks: 'Respiratory health', status: 'Follow-up', tone: 'purple' }];

export default function Patients() { const [query, setQuery] = useState(''); const filtered = patients.filter((patient) => patient.name.toLowerCase().includes(query.toLowerCase())); return <RequireRole role="doctor"><PortalShell role="doctor" title="Patients" subtitle="Review check-ins, health context, and next steps for your care group." action={<button className="header-cta"><Icon name="users" size={16} />Add patient</button>}><div className="portal-content"><div className="patients-tools"><div className="search-box"><Icon name="search" size={18} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search patients" /></div><div className="filter-bar portal-filter"><button className="active">All patients</button><button>Needs review</button><button>New this week</button></div></div><section className="surface-card patient-table-card"><div className="patient-table-header"><span>Patient</span><span>Latest check-in</span><span>Health checks</span><span>Status</span><span /></div>{filtered.map((patient) => <article className="patient-table-row" key={patient.name}><div><span className={`queue-avatar ${patient.tone}`}>{patient.initials}</span><span><b>{patient.name}</b><small>{patient.age} years · Patient since 2025</small></span></div><p>{patient.last}</p><p>{patient.checks}</p><span className={`queue-status ${patient.tone}`}>{patient.status}</span><button className="round-arrow"><Icon name="arrow" size={16} /></button></article>)}</section></div></PortalShell></RequireRole>; }
