'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import { Brand, Icon } from '../components';

const demoAccounts = {
  'patient@medikit.care': { password: 'Patient@123', name: 'Maya Patel', role: 'patient' },
  'doctor@medikit.care': { password: 'Doctor@123', name: 'Dr. Anika Rao', role: 'doctor' }
};

export default function SignIn() {
  const router = useRouter();
  const [role, setRole] = useState('patient'); const [email, setEmail] = useState('patient@medikit.care'); const [password, setPassword] = useState('Patient@123'); const [error, setError] = useState(''); const [showPassword, setShowPassword] = useState(false); const [loading, setLoading] = useState(false);
  useEffect(() => { if (new URLSearchParams(window.location.search).get('role') === 'doctor') chooseRole('doctor'); }, []);
  const chooseRole = (nextRole) => { setRole(nextRole); setEmail(nextRole === 'doctor' ? 'doctor@medikit.care' : 'patient@medikit.care'); setPassword(nextRole === 'doctor' ? 'Doctor@123' : 'Patient@123'); setError(''); };
  const submit = (event) => { event.preventDefault(); setLoading(true); setError(''); const custom = JSON.parse(window.localStorage.getItem('medikit-users') || '[]'); const account = demoAccounts[email.toLowerCase()] || custom.find((user) => user.email.toLowerCase() === email.toLowerCase()); window.setTimeout(() => { if (!account || account.password !== password) { setError('Those details don’t match our records. Please try again.'); setLoading(false); return; } if (account.role !== role) { setError(`This account is registered as a ${account.role === 'doctor' ? 'clinician' : 'patient'} account.`); setLoading(false); return; } window.localStorage.setItem('medikit-session', JSON.stringify({ name: account.name, email: account.email || email, role: account.role })); router.push(account.role === 'doctor' ? '/doctor' : '/portal'); }, 450); };
  return <main className="auth-page"><section className="auth-aside"><Brand light /><div className="auth-aside-copy"><span className="eyebrow"><span className="dot" />WELCOME TO MEDIKIT</span><h1>A more connected<br /><em>kind of care.</em></h1><p>One protected place for your health information, care team and next best step.</p></div><div className="aside-testimonial"><div className="proof-avatars"><span>M</span><span>A</span><span>R</span></div><p>“MediKit makes it easier to keep our care conversations focused on what matters.”</p><small>— A care team member</small></div></section><section className="auth-content"><div className="auth-mobile-brand"><Brand /></div><div className="auth-card"><Link className="back-link" href="/"><span>←</span> Back to MediKit</Link><span className="eyebrow">SECURE SIGN IN</span><h2>Welcome back.</h2><p className="auth-lead">Choose your workspace and sign in to continue.</p><div className="role-tabs"><button className={role === 'patient' ? 'active' : ''} onClick={() => chooseRole('patient')}><Icon name="user" size={17} />Patient</button><button className={role === 'doctor' ? 'active' : ''} onClick={() => chooseRole('doctor')}><Icon name="stethoscope" size={17} />Clinician</button></div><form onSubmit={submit}><label>Email address<input value={email} onChange={(e) => setEmail(e.target.value)} type="email" autoComplete="email" required /></label><label>Password<span className="password-field"><input value={password} onChange={(e) => setPassword(e.target.value)} type={showPassword ? 'text' : 'password'} autoComplete="current-password" required /><button type="button" onClick={() => setShowPassword(!showPassword)}>{showPassword ? 'Hide' : 'Show'}</button></span></label><div className="form-options"><label className="check-label"><input type="checkbox" /> Remember me</label><button type="button" className="link-button">Forgot password?</button></div>{error && <p className="form-error">{error}</p>}<button className="primary auth-submit" disabled={loading}>{loading ? 'Signing you in…' : 'Sign in securely'} <Icon name="arrow" size={17} /></button></form><p className="auth-switch">New to MediKit? <Link href="/register">Create an account</Link></p><div className="demo-note"><Icon name="lock" size={15} /><span><b>Demo access</b> is prefilled for this workspace.</span></div></div></section></main>;
}
