'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { checks, Icon } from '../../components';
import { PortalShell, RequireRole } from '../../portal-shell';
import { useI18n } from '../../i18n';

const copy = {
  en: { title: 'Health check history', subtitle: 'A clear record of your completed check-ins and wellbeing summaries.', action: 'Start a new check', eyebrow: 'YOUR CHECK-IN HISTORY', completed: 'Completed checks', all: 'All results', empty: 'No health checks yet', emptyText: 'Start your first short health check to build a personal history here.', start: 'Explore health checks', repeat: 'Repeat this check', completedOn: 'Completed', updated: 'Your history is private to this device in this prototype.', result: 'Result' },
  ta: { title: 'சுகாதார பரிசோதனை வரலாறு', subtitle: 'முடிக்கப்பட்ட சுகாதார பரிசோதனைகள் மற்றும் நலன் சுருக்கங்களின் தெளிவான பதிவு.', action: 'புதிய பரிசோதனையைத் தொடங்கு', eyebrow: 'உங்கள் பரிசோதனை வரலாறு', completed: 'முடிக்கப்பட்ட பரிசோதனைகள்', all: 'அனைத்து முடிவுகள்', empty: 'இன்னும் சுகாதார பரிசோதனைகள் இல்லை', emptyText: 'உங்கள் தனிப்பட்ட வரலாற்றை உருவாக்க முதல் குறுகிய சுகாதார பரிசோதனையைத் தொடங்குங்கள்.', start: 'சுகாதார பரிசோதனைகளை ஆராயுங்கள்', repeat: 'இந்தப் பரிசோதனையை மீண்டும் செய்', completedOn: 'முடிக்கப்பட்டது', updated: 'இந்த மாதிரியில் உங்கள் வரலாறு இந்தச் சாதனத்தில் தனிப்பட்டதாக உள்ளது.', result: 'முடிவு' },
  hi: { title: 'स्वास्थ्य जांच इतिहास', subtitle: 'आपकी पूरी की गई जांच और सेहत सारांश का स्पष्ट रिकॉर्ड।', action: 'नई जांच शुरू करें', eyebrow: 'आपकी जांच का इतिहास', completed: 'पूरी की गई जांच', all: 'सभी परिणाम', empty: 'अभी कोई स्वास्थ्य जांच नहीं है', emptyText: 'यहाँ अपना निजी इतिहास बनाने के लिए अपनी पहली छोटी स्वास्थ्य जांच शुरू करें।', start: 'स्वास्थ्य जांच देखें', repeat: 'यह जांच दोहराएं', completedOn: 'पूर्ण किया गया', updated: 'इस प्रोटोटाइप में आपका इतिहास इस डिवाइस पर निजी रहता है।', result: 'परिणाम' },
  te: { title: 'ఆరోగ్య పరీక్ష చరిత్ర', subtitle: 'మీ పూర్తయిన చెక్-ఇన్‌లు మరియు శ్రేయస్సు సారాంశాల స్పష్టమైన రికార్డు.', action: 'కొత్త పరీక్షను ప్రారంభించండి', eyebrow: 'మీ చెక్-ఇన్ చరిత్ర', completed: 'పూర్తయిన పరీక్షలు', all: 'అన్ని ఫలితాలు', empty: 'ఇంకా ఆరోగ్య పరీక్షలు లేవు', emptyText: 'ఇక్కడ మీ వ్యక్తిగత చరిత్రను రూపొందించడానికి మీ మొదటి చిన్న ఆరోగ్య పరీక్షను ప్రారంభించండి.', start: 'ఆరోగ్య పరీక్షలను చూడండి', repeat: 'ఈ పరీక్షను మళ్లీ చేయండి', completedOn: 'పూర్తయింది', updated: 'ఈ ప్రోటోటైప్‌లో మీ చరిత్ర ఈ పరికరంలో ప్రైవేట్‌గా ఉంటుంది.', result: 'ఫలితం' }
};

export default function HealthHistoryPage() {
  const { language } = useI18n(); const text = copy[language] || copy.en; const [history, setHistory] = useState({});
  useEffect(() => { setHistory(JSON.parse(window.localStorage.getItem('medikit-screenings') || '{}')); }, []);
  const records = useMemo(() => Object.entries(history).map(([id, value]) => ({ check: checks.find((item) => item.id === id), ...value })).filter((item) => item.check), [history]);
  return <RequireRole role="patient"><PortalShell title={text.title} subtitle={text.subtitle} action={<Link className="header-cta" href="/screening"><Icon name="clipboard" size={16} />{text.action}</Link>}><div className="portal-content dedicated-page"><section className="history-overview"><div><span className="eyebrow"><span className="dot" />{text.eyebrow}</span><h2>{text.all}</h2><p>{text.updated}</p></div><div className="history-total"><Icon name="clipboard" size={22} /><div><b>{records.length}</b><span>{text.completed}</span></div></div></section>{records.length ? <section className="full-history-list">{records.map(({ check, label, tone, completedAt }) => <article className="full-history-card" key={check.id}><span className={`history-check-icon ${tone || 'low'}`}><Icon name={check.icon} size={21} /></span><div className="history-check-main"><span className="eyebrow">{check.category} · {check.time}</span><h2>{check.title}</h2><p>{check.description}</p><small><Icon name="clock" size={14} />{text.completedOn} {completedAt}</small></div><div className="history-check-result"><span>{text.result}</span><b className={tone || 'low'}>{label}</b><Link href={`/screening?check=${check.id}`}>{text.repeat} <Icon name="arrow" size={15} /></Link></div></article>)}</section> : <section className="history-empty"><span><Icon name="clipboard" size={28} /></span><h2>{text.empty}</h2><p>{text.emptyText}</p><Link className="primary" href="/screening">{text.start} <Icon name="arrow" size={17} /></Link></section>}</div></PortalShell></RequireRole>;
}
