import Link from 'next/link';
import CardTapWelcome from './card-tap-welcome';
import { Brand, Icon } from './components';
import { LanguagePicker } from './i18n';

const features = [
  ['pulse', 'Know your baseline', 'A simple, guided picture of your wellbeing — designed around the moments that matter.'],
  ['stethoscope', 'Care when you need it', 'Book time with a qualified clinician and bring your health context to every conversation.'],
  ['shield', 'Your data, protected', 'Clear privacy controls and a space built for your personal health information.']
];

export default function Home() {
  return <main className="company-site">
    <header className="site-header"><Brand /><nav className="site-nav"><a href="#solutions">Solutions</a><a href="#how-it-works">How it works</a><a href="#for-clinicians">For clinicians</a></nav><div className="header-actions"><LanguagePicker compact /><Link className="sign-in" href="/signin">Sign in</Link><Link className="header-cta" href="/register">Get started <Icon name="arrow" size={16} /></Link></div></header>
    <CardTapWelcome />
    <section className="trust-strip"><p>One connected experience for your health.</p><div><span><Icon name="shield" size={17} />Privacy-led</span><span><Icon name="clock" size={17} />Built around your time</span><span><Icon name="heart" size={17} />Human-centered care</span></div></section>
    <section className="feature-section" id="solutions"><div className="section-intro"><span className="eyebrow">ONE PLACE FOR YOUR HEALTH</span><h2>Less guesswork.<br /><em>More confidence.</em></h2><p>We help turn everyday health information into a clearer view of how you&apos;re doing, and what may help next.</p></div><div className="feature-list">{features.map(([icon, title, description], index) => <article className="feature-row" key={title}><span className={`feature-icon fi-${index}`}><Icon name={icon} size={23} /></span><div><h3>{title}</h3><p>{description}</p></div><Icon name="arrow" size={18} /></article>)}</div></section>
    <section className="process-section" id="how-it-works"><div className="process-art"><div className="process-card card-one"><span><Icon name="clipboard" size={18} /></span><b>Health check complete</b><small>Your latest insights are ready</small></div><div className="process-card card-two"><span><Icon name="video" size={18} /></span><b>Care that feels close</b><small>Connect with your clinician</small></div><div className="process-stem" /><div className="process-leaf leaf-a" /><div className="process-leaf leaf-b" /></div><div className="process-copy"><span className="eyebrow">HOW MEDIKIT WORKS</span><h2>Thoughtful care, at every step.</h2><p>We combine the convenience of a modern health platform with the reassurance of a real care team.</p><ol><li><b>Check in</b><span>Take a quick health check tailored to what matters today.</span></li><li><b>See the picture</b><span>Understand clear, practical insights in your personal dashboard.</span></li><li><b>Talk to someone</b><span>Book a visit when you want a clinician&apos;s perspective.</span></li></ol><Link className="outline-button" href="/register">See your health space <Icon name="arrow" size={16} /></Link></div></section>
    <section className="clinician-section" id="for-clinicians"><div><span className="eyebrow"><span className="dot" />FOR CARE TEAMS</span><h2>Better context makes better care.</h2><p>Give your team a focused view of patient check-ins, appointment schedules, and the trends worth discussing — without the clutter.</p><Link className="white-button" href="/signin?role=doctor">Explore the clinician portal <Icon name="arrow" size={17} /></Link></div><div className="clinician-preview"><div className="preview-head"><span><Icon name="stethoscope" size={17} /></span><b>Today&apos;s care team</b><small>12 appointments · 4 follow-ups</small></div><div className="patient-preview"><span className="mini-avatar">MP</span><div><b>Maya Patel</b><small>Wellbeing check completed today</small></div><span className="status-good">Ready</span></div><div className="patient-preview"><span className="mini-avatar blue">AK</span><div><b>Arjun Kumar</b><small>Blood pressure follow-up</small></div><span className="status-warm">Review</span></div><div className="preview-chart"><span>Patient engagement</span><div className="bars"><i /><i /><i /><i /><i /><i /><i /></div></div></div></section>
    <section className="company-cta"><span className="eyebrow">YOUR HEALTH, YOUR WAY</span><h2>Start with one small check-in.</h2><p>It only takes a few minutes to build a clearer picture of your wellbeing.</p><Link className="primary" href="/register">Get started with MediKit <Icon name="arrow" size={18} /></Link></section>
    <footer className="site-footer"><div><Brand light /><p>Thoughtful preventive care, designed for real life.</p></div><div className="footer-links"><a href="#solutions">Solutions</a><a href="#for-clinicians">For clinicians</a><Link href="/signin">Sign in</Link><Link href="/register">Create account</Link></div><small>© 2026 MediKit. Health awareness support, not medical diagnosis.</small></footer>
  </main>;
}
