'use client';

import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { Icon, checks } from '../components';
import { PortalShell, RequireRole } from '../portal-shell';
import KioskMap from '../kiosk-map';

const defaultMedicines = [
  { id: 'metformin', name: 'Metformin', dosage: '500 mg', schedule: 'After breakfast', colour: 'green' },
  { id: 'vitamin-d', name: 'Vitamin D3', dosage: '1,000 IU', schedule: 'After dinner', colour: 'warm' }
];
const clinicVisits = [
  { date: '18 Aug', year: '2026', clinic: 'MediKit Clinic, Indiranagar', doctor: 'Dr. Anika Rao · General medicine', note: 'Wellbeing review and lifestyle plan', tone: 'green' },
  { date: '06 Jul', year: '2026', clinic: 'City Diagnostics', doctor: 'Lab visit · Preventive screening', note: 'Blood work and health baseline', tone: 'blue' },
  { date: '21 May', year: '2026', clinic: 'MediKit Clinic, Indiranagar', doctor: 'Dr. Vivek Shah · Cardiology', note: 'Routine heart-health discussion', tone: 'warm' }
];

function readableTime(value) {
  if (!value) return 'Updating now';
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? 'Updated just now' : `Updated ${date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`;
}

export default function PatientPortal() {
  const [completed, setCompleted] = useState({}); const [name, setName] = useState('Maya'); const [vitals, setVitals] = useState(null); const [vitalsStatus, setVitalsStatus] = useState('Connecting to device…'); const [abha, setAbha] = useState(''); const [showAbha, setShowAbha] = useState(false); const [abhaInput, setAbhaInput] = useState(''); const [medicines, setMedicines] = useState(defaultMedicines); const [showMedicine, setShowMedicine] = useState(false); const [medicineForm, setMedicineForm] = useState({ name: '', dosage: '', schedule: '' });
  const loadVitals = useCallback(async () => { try { const response = await fetch('/api/vitals', { cache: 'no-store' }); if (!response.ok) throw new Error(); const nextVitals = await response.json(); setVitals(nextVitals); setVitalsStatus(nextVitals.source || 'Connected device'); } catch { setVitalsStatus('Device feed unavailable'); } }, []);
  useEffect(() => { setCompleted(JSON.parse(window.localStorage.getItem('medikit-screenings') || '{}')); const session = JSON.parse(window.localStorage.getItem('medikit-session') || '{}'); setName(session.name?.split(' ')[0] || 'Maya'); setAbha(window.localStorage.getItem('medikit-abha') || ''); const savedMedicines = JSON.parse(window.localStorage.getItem('medikit-medicines') || 'null'); if (savedMedicines) setMedicines(savedMedicines); loadVitals(); const interval = window.setInterval(loadVitals, 10000); return () => window.clearInterval(interval); }, [loadVitals]);
  const done = Object.keys(completed).length; const next = checks.find((check) => !completed[check.id]) || checks[0];
  const linkAbha = (event) => { event.preventDefault(); const cleaned = abhaInput.trim(); if (!cleaned) return; setAbha(cleaned); window.localStorage.setItem('medikit-abha', cleaned); setShowAbha(false); };
  const addMedicine = (event) => { event.preventDefault(); if (!medicineForm.name.trim()) return; const nextMedicines = [...medicines, { id: String(Date.now()), ...medicineForm, colour: 'blue' }]; setMedicines(nextMedicines); window.localStorage.setItem('medikit-medicines', JSON.stringify(nextMedicines)); setMedicineForm({ name: '', dosage: '', schedule: '' }); setShowMedicine(false); };
  const removeMedicine = (id) => { const nextMedicines = medicines.filter((medicine) => medicine.id !== id); setMedicines(nextMedicines); window.localStorage.setItem('medikit-medicines', JSON.stringify(nextMedicines)); };
  return <RequireRole role="patient"><PortalShell title={`Good morning, ${name}.`} subtitle="Here’s a calm view of your health today." action={<Link className="header-cta" href="/screening">Start a check <Icon name="arrow" size={16} /></Link>}><div className="portal-content"><section className="portal-hero"><div><span className="eyebrow"><span className="dot" />YOUR WELLBEING SNAPSHOT</span><div className="portal-score"><div><strong>{done ? Math.max(70, 88 - done * 2) : '—'}<small>{done ? '/100' : ''}</small></strong><span>{done ? 'On a positive path' : 'Ready when you are'}</span></div><div><h2>{done ? 'Your health picture is taking shape.' : 'Start with a small check-in.'}</h2><p>{done ? `You’ve completed ${done} of ${checks.length} health checks. Keep the momentum going with one next step.` : 'Take your first short check to create a helpful view of your current wellbeing.'}</p><Link className="primary" href="/screening">{done ? 'Continue my checks' : 'Start my first check'} <Icon name="arrow" size={17} /></Link></div></div></div><div className="score-orbit"><div className="orbit-ring ring-one" /><div className="orbit-ring ring-two" /><span className="orb orb-one"><Icon name="heart" size={17} /></span><span className="orb orb-two"><Icon name="spark" size={16} /></span><span className="orb orb-three"><Icon name="shield" size={16} /></span><div className="main-orb"><Icon name="cross" size={27} /></div></div></section>
    <section className="live-vitals"><div className="vitals-heading"><div><span className="eyebrow"><span className="live-dot" />LIVE DEVICE DASHBOARD</span><h2>Today&apos;s vital signs</h2><p>{vitalsStatus} · {readableTime(vitals?.updatedAt)}</p></div><button className="outline-button" onClick={loadVitals}><Icon name="pulse" size={15} />Refresh live data</button></div><div className="vitals-grid"><article><span className="vital-icon heart-vital"><Icon name="heart" /></span><small>Heart rate</small><b>{vitals?.heartRate ?? '—'}<em> bpm</em></b><p>{vitals?.heartRate ? 'Within your usual range' : 'Waiting for device data'}</p></article><article><span className="vital-icon oxygen-vital"><Icon name="pulse" /></span><small>Blood oxygen</small><b>{vitals?.spo2 ?? '—'}<em>%</em></b><p>{vitals?.spo2 ? 'Good oxygen saturation' : 'Waiting for device data'}</p></article><article><span className="vital-icon pressure-vital"><Icon name="trend" /></span><small>Blood pressure</small><b>{vitals?.bloodPressure ?? '—'}<em> mmHg</em></b><p>{vitals?.bloodPressure ? 'Latest recorded reading' : 'Waiting for device data'}</p></article><article><span className="vital-icon temp-vital"><Icon name="spark" /></span><small>Temperature</small><b>{vitals?.temperature ?? '—'}<em> °C</em></b><p>{vitals?.temperature ? 'Latest recorded reading' : 'Waiting for device data'}</p></article></div><div className="vitals-footer"><span><Icon name="shield" size={14} />Vitals are shown for awareness, not diagnosis.</span><span><Icon name="clock" size={14} />Automatic refresh every 10 seconds</span></div></section>
    <KioskMap />
    <section className="metric-grid"><article><span className="metric-icon green"><Icon name="clipboard" /></span><div><small>Health checks</small><b>{done} <em>/ {checks.length}</em></b><p>{done ? 'Progress saved' : 'Ready to begin'}</p></div></article><article><span className="metric-icon peach"><Icon name="calendar" /></span><div><small>Next appointment</small><b>Thu, 10:30</b><p>Dr. Anika Rao</p></div></article><article><span className="metric-icon blue"><Icon name="pulse" /></span><div><small>Health focus</small><b>{done ? 'Wellbeing' : 'Baseline'}</b><p>{done ? 'Keep building habits' : 'Your first check'}</p></div></article></section>
    <section className="health-record-grid"><article id="abha" className="abha-card"><div className="card-heading"><div><span className="eyebrow"><Icon name="shield" size={12} /> HEALTH ID</span><h2>ABHA health record</h2></div><span className={abha ? 'abha-status linked' : 'abha-status'}>{abha ? 'Linked' : 'Not linked'}</span></div>{abha ? <><div className="abha-number"><span>ABHA ADDRESS</span><b>{abha}</b></div><p>Your personal health-record identifier is available in your MediKit profile.</p><button className="soft-button" onClick={() => { setAbhaInput(abha); setShowAbha(true); }}>Manage ABHA record <Icon name="arrow" size={15} /></button></> : <><p>Keep your health identity alongside your check-ins, medicines, and clinic history.</p><button className="primary" onClick={() => setShowAbha(true)}>Link ABHA card <Icon name="arrow" size={15} /></button><small className="local-note">Demo: this ID is stored only in this browser until official ABHA connectivity is configured.</small></>}</article><article id="clinic-visits" className="clinic-visits-card"><div className="card-heading"><div><span className="eyebrow">CLINIC HISTORY</span><h2>Previous visits</h2></div><button className="icon-plain"><Icon name="download" size={17} /></button></div><div className="visit-list">{clinicVisits.map((visit) => <div className="visit-row" key={visit.date}><span className={`visit-date ${visit.tone}`}><b>{visit.date.split(' ')[0]}</b><small>{visit.date.split(' ')[1].toUpperCase()}</small></span><div><b>{visit.clinic}</b><p>{visit.doctor}</p><small>{visit.note} · {visit.year}</small></div><button className="round-arrow"><Icon name="arrow" size={15} /></button></div>)}</div><Link className="card-footer-link" href="/appointments">View all care history <Icon name="arrow" size={15} /></Link></article></section>
    <section id="medicines" className="medicine-section surface-card"><div className="card-heading"><div><span className="eyebrow">MEDICINES</span><h2>Your medicine plan</h2><p>Keep a simple list of the medicines and supplements you’re taking.</p></div><button className="outline-button" onClick={() => setShowMedicine(true)}>Add medicine <Icon name="arrow" size={15} /></button></div><div className="medicine-list">{medicines.length ? medicines.map((medicine) => <article key={medicine.id}><span className={`medicine-icon ${medicine.colour}`}><Icon name="beaker" size={18} /></span><div><b>{medicine.name}</b><p>{medicine.dosage || 'Dosage not added'} · {medicine.schedule || 'Schedule not added'}</p></div><span className="medicine-active">Active</span><button className="icon-plain" onClick={() => removeMedicine(medicine.id)} aria-label={`Remove ${medicine.name}`}><Icon name="close" size={17} /></button></article>) : <div className="empty-state"><span><Icon name="beaker" size={22} /></span><div><b>No medicines added yet.</b><p>Add a medicine or supplement to keep your health summary current.</p></div></div>}</div></section>
    <section className="portal-two-col"><div className="surface-card"><div className="card-heading"><div><span className="eyebrow">COMPLETE TESTING HUB</span><h2>One small step today.</h2></div><Link href="/screening">View all tests <Icon name="arrow" size={15} /></Link></div><div className="recommendation"><span className="recommend-icon"><Icon name={next.icon} size={23} /></span><div><b>{next.title}</b><p>{next.description}</p><span className="mini-detail"><Icon name="clock" size={13} /> {next.time} · private & saved on this device</span></div><Link href={`/screening?check=${next.id}`} className="round-arrow"><Icon name="arrow" size={17} /></Link></div></div><div className="surface-card appointment-card"><div className="card-heading"><div><span className="eyebrow">UPCOMING CARE</span><h2>Your next visit.</h2></div><Link href="/appointments">Manage <Icon name="arrow" size={15} /></Link></div><div className="appointment-preview"><span className="date-block"><b>05</b><small>SEP</small></span><div><b>Dr. Anika Rao</b><p>General medicine · Video visit</p><span><Icon name="clock" size={13} />10:30 AM – 10:50 AM</span></div></div><Link href="/appointments" className="soft-button">View appointment details</Link></div></section>
    <section className="history-section"><div className="card-heading"><div><span className="eyebrow">YOUR ACTIVITY</span><h2>Health check history</h2></div><Link href="/screening">Take another check <Icon name="arrow" size={15} /></Link></div>{done ? <div className="activity-list">{Object.entries(completed).map(([id, data]) => { const check = checks.find((item) => item.id === id); return <div key={id}><span className="activity-icon"><Icon name={check?.icon || 'clipboard'} size={18} /></span><div><b>{check?.title || 'Health check'}</b><p>Completed {data.completedAt} · <strong className={`status-text ${data.tone}`}>{data.label}</strong></p></div><Link href={`/screening?check=${id}`}><Icon name="arrow" size={17} /></Link></div>; })}</div> : <div className="empty-state"><span><Icon name="clipboard" size={22} /></span><div><b>Your check history is empty.</b><p>Start your first health check and your insights will appear here.</p></div></div>}</section></div>
    {showAbha && <div className="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="abha-title"><div className="assessment-modal compact-modal"><button className="close-modal" onClick={() => setShowAbha(false)} aria-label="Close"><Icon name="close" /></button><div className="modal-icon"><Icon name="shield" size={26} /></div><span className="eyebrow">HEALTH ID</span><h2 id="abha-title">{abha ? 'Manage your ABHA record' : 'Link your ABHA card'}</h2><p>Enter the ABHA address or number you use to identify your health record.</p><form onSubmit={linkAbha}><label className="field">ABHA address or number<input value={abhaInput} onChange={(event) => setAbhaInput(event.target.value)} placeholder="e.g. name@abdm or 12-3456-7890-1234" required /></label><p className="privacy-copy"><Icon name="lock" size={14} />For this prototype, your ABHA identifier stays in this browser. Official ABDM verification requires approved credentials and consent integration.</p><button className="primary full">Save ABHA record <Icon name="arrow" size={17} /></button></form></div></div>}
    {showMedicine && <div className="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="medicine-title"><div className="assessment-modal compact-modal"><button className="close-modal" onClick={() => setShowMedicine(false)} aria-label="Close"><Icon name="close" /></button><div className="modal-icon"><Icon name="beaker" size={26} /></div><span className="eyebrow">MEDICINE PLAN</span><h2 id="medicine-title">Add a medicine</h2><p>Keep this list up to date so it is easy to review with your care team.</p><form onSubmit={addMedicine}><label className="field">Medicine or supplement name<input value={medicineForm.name} onChange={(event) => setMedicineForm({ ...medicineForm, name: event.target.value })} placeholder="e.g. Vitamin B12" required /></label><div className="form-two-col"><label className="field">Dosage<input value={medicineForm.dosage} onChange={(event) => setMedicineForm({ ...medicineForm, dosage: event.target.value })} placeholder="e.g. 500 mg" /></label><label className="field">When do you take it?<input value={medicineForm.schedule} onChange={(event) => setMedicineForm({ ...medicineForm, schedule: event.target.value })} placeholder="e.g. After lunch" /></label></div><button className="primary full">Add to medicine plan <Icon name="arrow" size={17} /></button></form></div></div>}</PortalShell></RequireRole>;
}
