'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { Brand, Icon } from '../components';

export default function Register() {
  const router = useRouter(); const [role, setRole] = useState('patient'); const [form, setForm] = useState({ name: '', email: '', password: '', agree: false }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const setValue = (key, value) => setForm({ ...form, [key]: value });
  const submit = (event) => { event.preventDefault(); setError(''); if (form.password.length < 8) return setError('Use a password with at least 8 characters.'); if (!form.agree) return setError('Please confirm the privacy terms to continue.'); setLoading(true); const users = JSON.parse(window.localStorage.getItem('medikit-users') || '[]'); if (users.some((user) => user.email.toLowerCase() === form.email.toLowerCase())) { setError('An account already exists with this email.'); setLoading(false); return; } const user = { ...form, role }; users.push(user); window.localStorage.setItem('medikit-users', JSON.stringify(users)); window.localStorage.setItem('medikit-session', JSON.stringify({ name: user.name, email: user.email, role: user.role })); window.setTimeout(() => router.push(role === 'doctor' ? '/doctor' : '/portal'), 350); };
  return <main className="auth-page register-page"><section className="auth-aside"><Brand light /><div className="auth-aside-copy"><span className="eyebrow"><span className="dot" />GET STARTED</span><h1>Make space for<br /><em>your wellbeing.</em></h1><p>Set up your personal health space in a minute. Your first check-in is waiting.</p></div><ul className="signup-points"><li><span><Icon name="check" size={15} /></span>Private health space</li><li><span><Icon name="check" size={15} /></span>Guided health checks</li><li><span><Icon name="check" size={15} /></span>Care-team appointments</li></ul></section><section className="auth-content"><div className="auth-mobile-brand"><Brand /></div><div className="auth-card"><Link className="back-link" href="/"><span>←</span> Back to MediKit</Link><span className="eyebrow">CREATE YOUR ACCOUNT</span><h2>Let&apos;s get started.</h2><p className="auth-lead">Choose the space you need. You can update your profile later.</p><div className="account-cards"><button onClick={() => setRole('patient')} className={role === 'patient' ? 'selected' : ''}><Icon name="user" size={20} /><span><b>I&apos;m a patient</b><small>Track my health and care</small></span><i><Icon name="check" size={13} /></i></button><button onClick={() => setRole('doctor')} className={role === 'doctor' ? 'selected' : ''}><Icon name="stethoscope" size={20} /><span><b>I&apos;m a clinician</b><small>Manage my care workspace</small></span><i><Icon name="check" size={13} /></i></button></div><form onSubmit={submit}><label>Full name<input value={form.name} onChange={(e) => setValue('name', e.target.value)} placeholder="e.g. Maya Patel" autoComplete="name" required /></label><label>Email address<input value={form.email} onChange={(e) => setValue('email', e.target.value)} type="email" placeholder="you@example.com" autoComplete="email" required /></label><label>Create a password<input value={form.password} onChange={(e) => setValue('password', e.target.value)} type="password" placeholder="At least 8 characters" autoComplete="new-password" required /></label><label className="terms-check"><input checked={form.agree} onChange={(e) => setValue('agree', e.target.checked)} type="checkbox" /><span>I agree to the <button type="button" className="link-button">Terms</button> and <button type="button" className="link-button">Privacy Policy</button>.</span></label>{error && <p className="form-error">{error}</p>}<button className="primary auth-submit" disabled={loading}>{loading ? 'Creating your space…' : 'Create my health space'} <Icon name="arrow" size={17} /></button></form><p className="auth-switch">Already have an account? <Link href="/signin">Sign in</Link></p></div></section></main>;
}
